version: '3.8'

services:
  redis:
    image: bitnami/redis:latest
    container_name: match_engine_redis
    network_mode: host
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=6379
    volumes:
      - redis_data:/bitnami/redis/data
    restart: unless-stopped

  matcher:
    build: .
    container_name: matcher
    network_mode: host
    env_file:
      - .env
    volumes:
      - matcher_data:/app/data
    restart: unless-stopped
    depends_on:
      - redis

volumes:
  redis_data:
    driver: local

  matcher_data:
    driver: local